# Generated by Django 6.0.6 on 2026-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradehistory',
            name='duty',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
