# Generated by Django 5.2.17 on 2026-10-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_ptpa_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PtpaAttendance',
        ),
    ]
