# Generated by Django 5.2.17 on 2026-09-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STEM', 'STEM'), ('TVL', 'TVL'), ('HUMSS', 'HUMSS'), ('ICT', 'ICT'), ('GAS', 'GAS')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'school_programs',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 2025-2026', max_length=9, unique=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_years',
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('grade_level', models.CharField(db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='school.program')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.schoolyear')),
            ],
            options={
                'db_table': 'school_sections',
                'ordering': ['grade_level', 'name'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'name'), name='unique_section_name_per_year')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed')], default='upcoming', max_length=16)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='school.schoolyear')),
            ],
            options={
                'db_table': 'school_terms',
                'ordering': ['school_year', 'number'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'number'), name='unique_term_per_year'), models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 3)), name='term_number_1_to_3')],
            },
        ),
    ]
