# Generated by Django 6.0.6 on 2026-09-22 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_grade11_clusters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('applied', 'Applied'), ('specialized', 'Specialized')], max_length=16)),
                ('term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='school.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_links', to='school.subject')),
            ],
            options={
                'db_table': 'school_program_subjects',
                'ordering': ['program', 'kind', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('program', 'subject'), name='unique_subject_per_program'), models.CheckConstraint(condition=models.Q(('term__isnull', True), models.Q(('term__gte', 1), ('term__lte', 3)), _connector='OR'), name='program_subject_term_1_to_3')],
            },
        ),
    ]
