# Generated by Django 6.0.6 on 2026-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_program_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='encode_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='encode_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
