# Generated by Django 5.2.17 on 2026-09-29 21:30

import django.db.models.deletion
from django.db import migrations, models


def seed_reference(apps, schema_editor):
    from apps.school.offerings import seed_academic_reference
    from apps.school.program_catalog import CURRICULUM_BY_GRADE

    seed_academic_reference(apps.get_model)

    # Years that already exist were run under the transition layout; record it so it stays true.
    school_year_model = apps.get_model('school', 'SchoolYear')
    curriculum_model = apps.get_model('school', 'Curriculum')
    year_curriculum_model = apps.get_model('school', 'SchoolYearCurriculum')
    for year in school_year_model.objects.all():
        for grade_level, code in CURRICULUM_BY_GRADE.items():
            year_curriculum_model.objects.get_or_create(
                school_year=year,
                grade_level=grade_level,
                defaults={'curriculum': curriculum_model.objects.get(code=code)},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_section_status_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'school_curricula',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'school_skill_domains',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='continues_to',
            field=models.ForeignKey(blank=True, help_text='Grade 12 program this Grade 11 program leads to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continued_from', to='school.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='school.curriculum'),
        ),
        migrations.AddField(
            model_name='subject',
            name='skill_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.skilldomain'),
        ),
        migrations.CreateModel(
            name='SchoolYearCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=16)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_years', to='school.curriculum')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='school.schoolyear')),
            ],
            options={
                'db_table': 'school_year_curricula',
                'ordering': ['school_year', 'grade_level'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'grade_level'), name='one_curriculum_per_year_grade')],
            },
        ),
        migrations.RunPython(seed_reference, migrations.RunPython.noop),
    ]
