# Generated by Django 5.2.17 on 2026-09-30 14:50

from django.db import migrations, models


def mark_excluded(apps, schema_editor):
    from apps.school.offerings import seed_matching_exclusions

    seed_matching_exclusions(apps.get_model)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_research_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='matching_excluded',
            field=models.BooleanField(default=False, help_text='Deliberately left out of college matching (e.g. PE). A subject with no skill domain and this unticked is reported as unmapped.'),
        ),
        migrations.RunPython(mark_excluded, migrations.RunPython.noop),
    ]
