# Generated by Django 5.2.17 on 2026-10-04 16:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_subject_term_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='retention_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text="Percent of this year's approved Grade 11 students expected to continue to Grade 12 next year. An assumption set by the Admin, used only for the planning estimate.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
