# Generated by Django 5.2.17 on 2026-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_school_year_retention_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='strand_group',
            field=models.CharField(blank=True, help_text='Stable strand group across curricula (e.g. STEM for STEM and STEMC). Read by the college recommender.', max_length=16),
        ),
    ]
