# Generated by Django 6.0.6 on 2026-09-28 07:38

from django.db import migrations, models


def backfill_notification_category(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    from apps.audit.catalog import infer_notification_category

    for row in Notification.objects.all().iterator():
        category = infer_notification_category(row.title, row.body)
        if row.category != category:
            row.category = category
            row.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_level_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('accounts', 'accounts'), ('school', 'school'), ('assignments', 'assignments'), ('placement', 'placement'), ('grades', 'grades'), ('announcements', 'announcements')], db_index=True, default='accounts', max_length=16),
        ),
        migrations.RunPython(backfill_notification_category, migrations.RunPython.noop),
    ]
