# Generated by Django 5.2.17 on 2026-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_guidance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('accounts', 'accounts'), ('school', 'school'), ('assignments', 'assignments'), ('placement', 'placement'), ('grades', 'grades'), ('announcements', 'announcements'), ('access', 'access'), ('guidance', 'guidance'), ('security', 'security')], db_index=True, default='accounts', max_length=16),
        ),
    ]
