# Generated by Django 6.0.6 on 2026-09-28 07:38

from django.db import migrations, models


def backfill_audit_family(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    from apps.audit.catalog import family_for_action

    for row in AuditLog.objects.all().iterator():
        family = family_for_action(row.action)
        if row.family != family:
            row.family = family
            row.save(update_fields=['family'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='family',
            field=models.CharField(choices=[('accounts', 'accounts'), ('school', 'school'), ('assignments', 'assignments'), ('placement', 'placement'), ('grades', 'grades'), ('announcements', 'announcements')], db_index=True, default='accounts', max_length=16),
        ),
        migrations.RunPython(backfill_audit_family, migrations.RunPython.noop),
    ]
