# Generated by Django 5.2.17 on 2026-10-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_mail_activation_log'),
        ('ml', '0007_seed_recommender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_notes', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'guidance_adviser_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('license_url', models.URLField(blank=True)),
                ('attribution', models.TextField(help_text='Shown to students on the assessment screen, as the license requires.')),
                ('license_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pilot_status', models.CharField(choices=[('not_piloted', 'Not yet piloted'), ('piloted', 'Piloted')], default='not_piloted', max_length=12)),
                ('pilot_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('active_marker', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('license_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guidance_instruments',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InterestAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=12)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('open_marker', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_assessments', to='accounts.studentprofile')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='guidance.interestinstrument')),
            ],
            options={
                'db_table': 'guidance_assessments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('original_text', models.CharField(max_length=255)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('riasec', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='guidance.interestinstrument')),
            ],
            options={
                'db_table': 'guidance_questions',
                'ordering': ['instrument', 'position'],
            },
        ),
        migrations.CreateModel(
            name='InterestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='guidance.interestassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='guidance.interestquestion')),
            ],
            options={
                'db_table': 'guidance_responses',
            },
        ),
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('profile_matching', 'Profile matching'), ('hybrid_ml', 'Machine learning with profile matching')], max_length=20)),
                ('instrument_version', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_schema', models.CharField(max_length=16)),
                ('catalog_version', models.CharField(max_length=16)),
                ('features', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ready', models.BooleanField(default=False)),
                ('not_ready_reason', models.CharField(blank=True, max_length=32)),
                ('fallback_reason', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='guidance.interestassessment')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ml.recommenderconfig')),
                ('family_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ml.modelrun')),
                ('program_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ml.modelrun')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'guidance_recommendation_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('tier', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Explore more')], max_length=12)),
                ('label', models.CharField(choices=[('strong', 'Strong Match'), ('good', 'Good Match'), ('possible', 'Possible Match'), ('limited', 'Limited Evidence')], max_length=12)),
                ('evidence', models.JSONField(default=dict)),
                ('college_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ml.collegeprogram')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guidance.recommendationrun')),
            ],
            options={
                'db_table': 'guidance_recommendation_items',
                'ordering': ['run', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='AdviserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('college_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ml.collegeprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser_recommendations', to='accounts.studentprofile')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='guidance.recommendationrun')),
            ],
            options={
                'db_table': 'guidance_adviser_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('source', models.CharField(choices=[('screen', 'Requested on the readiness screen'), ('command', 'Started by the management command')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('open_marker', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ml.recommenderconfig')),
                ('family_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ml.modelrun')),
                ('program_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ml.modelrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guidance_training_jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assessment', 'Take the assessment and receive recommendations'), ('training', 'Use pseudonymous data to improve the recommender')], max_length=12)),
                ('party', models.CharField(choices=[('student', 'Student (18 or older)'), ('student_and_guardian', 'Student, with parent or guardian consent')], max_length=24)),
                ('notice_version', models.CharField(max_length=16)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('active_marker', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_consents', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'guidance_consents',
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['student', 'kind'], name='guidance_consent_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='interestinstrument',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='one_instrument_version'),
        ),
        migrations.AddIndex(
            model_name='interestassessment',
            index=models.Index(fields=['student', 'status'], name='guidance_assessment_lookup'),
        ),
        migrations.AddConstraint(
            model_name='interestquestion',
            constraint=models.UniqueConstraint(fields=('instrument', 'position'), name='one_question_per_position'),
        ),
        migrations.AddConstraint(
            model_name='interestresponse',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='one_response_per_question'),
        ),
        migrations.AddConstraint(
            model_name='interestresponse',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='response_value_1_to_5'),
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['student', '-created_at'], name='guidance_run_latest'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('run', 'rank'), name='one_item_per_rank'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('run', 'college_program'), name='one_item_per_program'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='item_rank_from_one'),
        ),
    ]
