# Generated by Django 6.0.6 on 2026-09-22 16:20

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailcode_head_teacher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.PortalUserManager()),
            ],
        ),
    ]
