# Generated by Django 5.2.17 on 2026-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('prefer_not_to_say', 'Prefer not to say')], max_length=32),
        ),
    ]
