# Generated by Django 5.2.17 on 2026-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_gender_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Wrong guesses so far; too many cancel the code.'),
        ),
    ]
