# Generated by Django 6.0.6 on 2026-10-03 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_email_code_attempts'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Registration result'), ('code', 'Code'), ('notice', 'Account notice')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='people.registration')),
            ],
            options={
                'db_table': 'accounts_mail_outbox',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='mail_outbox_due'), models.Index(fields=['sent_at'], name='mail_outbox_sent_at')],
            },
        ),
    ]
