# Generated by Django 6.0.6 on 2026-10-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mail_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailoutbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailoutbox',
            name='kind',
            field=models.CharField(choices=[('registration', 'Registration result'), ('activation', 'Activation code'), ('code', 'Password code'), ('notice', 'Account notice')], max_length=16),
        ),
    ]
