# Generated by Django 5.2.17 on 2026-10-05 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mail_activation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('logout', 'Signed out'), ('idle', 'Idle too long'), ('expired', 'Session time limit reached'), ('password', 'Password changed or reset'), ('account', 'Account can no longer sign in'), ('replay', 'A used refresh token came back'), ('admin', 'Signed out by an administrator')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.authsession')),
            ],
            options={
                'db_table': 'accounts_session_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'ended_at'], name='auth_session_user_open'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['expires_at'], name='auth_session_expires'),
        ),
    ]
