# Generated by Django 6.0.6 on 2026-10-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_authenticator_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverycode',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthenticatorDevice',
        ),
        migrations.DeleteModel(
            name='RecoveryCode',
        ),
    ]
