import { useAuth } from '../../context/AuthContext';

const ROLE_LABEL = { student: 'Student', teacher: 'Teacher', head_teacher: 'Head teacher', admin: 'Administrator' };

function formatWhen(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleString('en-PH', { year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' });
}

/** Every printed report says when it was made, by which account, and that it holds personal data (plan W15). */
export default function PrintFooter({ generatedAt }) {
  const { user } = useAuth();
  return (
    <footer className="gp-foot">
      <span>Date generated: {formatWhen(generatedAt)}</span>
      {user ? (
        <span>
          Generated by: {ROLE_LABEL[user.role] || user.role} · account #{user.id}
        </span>
      ) : null}
      <span className="gp-confidential">
        Confidential: contains student personal information protected by the Data Privacy Act of 2012 (RA 10173). Do
        not share, post or leave unattended.
      </span>
    </footer>
  );
}
