# Generated by Django 5.2.17 on 2026-09-29 21:32

import django.db.models.deletion
from django.db import migrations, models


def seed_and_backfill(apps, schema_editor):
    from apps.ml.seed import seed_college_programs

    seed_college_programs(apps.get_model)

    program_model = apps.get_model('school', 'Program')
    snapshot_model = apps.get_model('ml', 'ClusterSnapshot')
    year_curriculum_model = apps.get_model('school', 'SchoolYearCurriculum')
    programs = {row.code: row for row in program_model.objects.all()}
    grade11 = dict(
        year_curriculum_model.objects.filter(grade_level='Grade 11').values_list('school_year_id', 'curriculum_id')
    )
    for snapshot in snapshot_model.objects.filter(program__isnull=True):
        program = programs.get(snapshot.cluster_code)
        if program is None:
            continue
        snapshot.program = program
        snapshot.curriculum_id = grade11.get(snapshot.school_year_id, program.curriculum_id)
        snapshot.save(update_fields=['program', 'curriculum'])

    run_model = apps.get_model('ml', 'ModelRun')
    versions = {}
    for run in run_model.objects.order_by('trained_at', 'id'):
        versions[run.name] = versions.get(run.name, 0) + 1
        run.version = versions[run.name]
        run.save(update_fields=['version'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_archive'),
        ('ml', '0001_initial'),
        ('school', '0010_curriculum_skill_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_snapshots', to='school.curriculum'),
        ),
        migrations.AddField(
            model_name='clustersnapshot',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_snapshots', to='school.program'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='curriculum_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='dataset',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='feature_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('shs_programs', models.ManyToManyField(blank=True, help_text='SHS programs that lead naturally to this course.', related_name='college_programs', to='school.program')),
            ],
            options={
                'db_table': 'ml_college_programs',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CollegeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college_outcomes', to='school.schoolyear')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_outcome', to='accounts.studentprofile')),
                ('college_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='ml.collegeprogram')),
            ],
            options={
                'db_table': 'ml_college_outcomes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeProgramSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('college_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ml.collegeprogram')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college_skills', to='school.skilldomain')),
            ],
            options={
                'db_table': 'ml_college_program_skills',
                'ordering': ['college_program', 'domain__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('college_program', 'domain'), name='one_skill_row_per_domain')],
            },
        ),
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
    ]
