# Generated by Django 5.2.17 on 2026-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_drop_synthetic_knn_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='is_synthetic',
            field=models.BooleanField(default=False, help_text='Invented history written by seed_demo_forecast in a demo database. Never true for real years.'),
        ),
    ]
