# Generated by Django 5.2.17 on 2026-10-05 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mail_activation_log'),
        ('ml', '0005_snapshot_is_synthetic'),
        ('school', '0015_program_strand_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInterestMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riasec', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1)),
            ],
            options={
                'db_table': 'ml_family_interest_map',
                'ordering': ['family', 'riasec'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.BinaryField()),
                ('signature', models.CharField(max_length=64)),
                ('sklearn_version', models.CharField(max_length=16)),
                ('numpy_version', models.CharField(max_length=16)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_model_artifacts',
            },
        ),
        migrations.CreateModel(
            name='ProgramFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'ml_program_families',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft, not yet validated'), ('validated', 'Validated by experts')], max_length=12)),
                ('rows', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('validators', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_program_profile_snapshots',
                'ordering': ['college_program', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(help_text='The profile version these ratings will produce.')),
                ('level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('benchmark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_program_skill_ratings',
                'ordering': ['college_program', 'round', 'domain__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecommenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('values', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=False, help_text='True once the school panel has approved these values; until then they are provisional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('active_marker', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
            options={
                'db_table': 'ml_recommender_configs',
                'ordering': ['-version'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelrun',
            options={'ordering': ['-trained_at'], 'permissions': [('train_recommender', 'Can queue college recommender training'), ('activate_recommender', 'Can activate or roll back college recommender models')]},
        ),
        migrations.AddField(
            model_name='collegeoutcome',
            name='is_synthetic',
            field=models.BooleanField(default=False, help_text='Invented by a demo seed. Production training never reads synthetic outcomes.'),
        ),
        migrations.AddField(
            model_name='collegeoutcome',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegeoutcome',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('validated', 'Validated')], db_index=True, default='recorded', max_length=12),
        ),
        migrations.AddField(
            model_name='collegeoutcome',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeoutcome',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='career_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft, not yet validated'), ('validated', 'Validated by experts')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='profile_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='source',
            field=models.CharField(blank=True, help_text='Authoritative source, such as a CHED issuance.', max_length=255),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='verified_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegeprogramskill',
            name='minimum_kind',
            field=models.CharField(choices=[('benchmark', 'Profile benchmark'), ('official', 'Official requirement')], default='benchmark', max_length=12),
        ),
        migrations.AddField(
            model_name='collegeprogramskill',
            name='requirement_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='active_marker',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='status',
            field=models.CharField(blank=True, choices=[('trained', 'Trained'), ('evaluated', 'Evaluated'), ('candidate', 'Candidate'), ('active', 'Active'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='name',
            field=models.CharField(help_text='Official program name.', max_length=160),
        ),
        migrations.AddConstraint(
            model_name='collegeoutcome',
            constraint=models.CheckConstraint(condition=models.Q(('validated_by__isnull', True), ('recorded_by__isnull', True), models.Q(('validated_by', models.F('recorded_by')), _negated=True), _connector='OR'), name='outcome_validated_by_second_person'),
        ),
        migrations.AddConstraint(
            model_name='collegeprogramskill',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 0), ('level__lte', 100)), name='college_skill_level_in_range'),
        ),
        migrations.AddConstraint(
            model_name='collegeprogramskill',
            constraint=models.CheckConstraint(condition=models.Q(('minimum__isnull', True), models.Q(('minimum__gte', 0), ('minimum__lte', 100)), _connector='OR'), name='college_skill_minimum_in_range'),
        ),
        migrations.AddConstraint(
            model_name='collegeprogramskill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minimum_kind', 'official'), _negated=True), models.Q(('minimum__isnull', False), models.Q(('requirement_source', ''), _negated=True)), _connector='OR'), name='official_requirement_has_source'),
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary', to='ml.modelrun'),
        ),
        migrations.AddField(
            model_name='familyinterestmap',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_types', to='ml.programfamily'),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='ml.programfamily'),
        ),
        migrations.AddField(
            model_name='programprofilesnapshot',
            name='college_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to='ml.collegeprogram'),
        ),
        migrations.AddField(
            model_name='programprofilesnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programskillrating',
            name='college_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ml.collegeprogram'),
        ),
        migrations.AddField(
            model_name='programskillrating',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school.skilldomain'),
        ),
        migrations.AddField(
            model_name='programskillrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommenderconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='familyinterestmap',
            constraint=models.UniqueConstraint(fields=('family', 'riasec'), name='one_interest_type_per_family'),
        ),
        migrations.AddConstraint(
            model_name='programprofilesnapshot',
            constraint=models.UniqueConstraint(fields=('college_program', 'version'), name='one_snapshot_per_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='programskillrating',
            constraint=models.UniqueConstraint(fields=('college_program', 'domain', 'rater', 'round'), name='one_rating_per_rater_round'),
        ),
        migrations.AddConstraint(
            model_name='programskillrating',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 0), ('level__lte', 100)), name='rating_level_in_range'),
        ),
        migrations.AddConstraint(
            model_name='programskillrating',
            constraint=models.CheckConstraint(condition=models.Q(('benchmark__isnull', True), models.Q(('benchmark__gte', 0), ('benchmark__lte', 100)), _connector='OR'), name='rating_benchmark_in_range'),
        ),
    ]
