# Generated by Django 5.2.17 on 2026-10-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='changes',
            field=models.JSONField(blank=True, default=list, help_text='Before and after, field by field, as it stood when the request was submitted.'),
        ),
    ]
